# Generated by Django 2.0.4 on 2018-04-27 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(help_text='Name of the route', max_length=200)),
                ('quantity_places', models.IntegerField()),
                ('driver', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(help_text='Name of the route', max_length=200)),
                ('route_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_trip', models.CharField(choices=[('ПН', 'MON'), ('ВТ', 'TUE'), ('СР', 'WED'), ('ВТ', 'TUE'), ('СР', 'WED'), ('ЧТ', 'THU'), ('ПТ', 'FRI')], default='MON', max_length=10)),
                ('time_trip', models.TimeField()),
                ('car', models.ForeignKey(on_delete=None, to='booking.Car')),
                ('route', models.ForeignKey(on_delete=None, to='booking.Route')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=None, to='booking.Trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
