# Generated by Django 2.0.4 on 2018-05-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Driver', 'Driver')], default='Faculty', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of User'),
        ),
    ]
